version: "3"

networks:
  loki:

services:
  loki:
    container_name: gafana-loki
    image: grafana/loki:latest
    volumes:
      - /loki/config:/loki/config
      - /loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/loki/config/loki-config.yaml
    networks:
      - loki

  promtail:
    container_name: loki-promtail
    image: grafana/promtail:latest
    ports:
      - "1514:1514"
    volumes:
      - /var/log:/var/log
      - /loki/config:/loki/config 
    command: -config.file=/loki/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
